version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: sms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quanlysinhvien_v2
      MYSQL_USER: sms_user
      MYSQL_PASSWORD: sms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
