spring.application.name=quanlysinhvien

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/quanlysinhvien
spring.data.mongodb.database=quanlysinhvien

# Server port
server.port=8080

# CORS
spring.web.cors.allowed-origins=http://localhost:5173
